import express from "express";
import { getPool } from '../db.js';

const router = express.Router();

/** 
 * GET all genres
 * /api/genres
 */
router.get('/', async (req, res) => {
  try {
    const pool = await getPool();
    const result = await pool.request().query("SELECT * FROM Genres");
    res.json(result.recordset);
  } catch (err) {
    console.error("Error fetching genres:", err);
    res.status(500).json({ error: "Failed to fetch genres" });
  }
});

/**
 * GET a specific genre
 * /api/genres/:id
 */ 
router.get('/:id', async (req, res) => {
  const genreId = req.params.id;
  try {
    const pool = await getPool();
    const result = await pool
      .request()
      .input('GenreId', genreId)
      .query('SELECT * FROM Genres WHERE GenreId = @GenreId');
    if (result.recordset.length === 0) {
      return res.status(404).json({ error: "Genre not found" });
    }
    res.json(result.recordset[0]);
  } catch (error) {
    console.error("Error fetching genre:", error);
    res.status(500).json({ error: "Internal server error" });
  }
});

/**
 * POST (create) a new genre
 * /api/genre
 */
router.post('/', async (req, res) => {
  const { Name } = req.body;
  if (!Name) {
    return res.status(400).json({ error: "Name is required" });
  }
  try {
    const pool = await getPool();
    const result = await pool.request()
      .input("Name", Name)
      .query(`INSERT INTO Genres (Name) OUTPUT INSERTED.* VALUES (@Name)`);
    // result.recordset[0] contains the new row, including the autogenerated GenreId
    res.status(201).json(result.recordset[0]);
  } catch (err) {
    console.error("Error inserting genre:", err);
    res.status(500).json({ error: "Internal server error" });
  }
});

/**
 * PUT (update) a genre
 * /api/genre/:id
 */
router.put('/:id', async (req, res) => {
  const { id } = req.params;
  const { Name } = req.body;
  const query = `UPDATE Genres SET Name = @Name WHERE GenreId = @GenreId`;
  try {
    const pool = await getPool();
    await pool.request()
      .input('GenreId', id)
      .input('Name', Name)
      .query(query);
    res.json({ message: "Genre updated successfully" });
  } catch (error) {
    console.error("Error updating genre:", error);
    res.status(500).json({ error: "Internal server error" });
  }
});

/**
 * DELETE a genre
 * /api/genre/:id
 */
router.delete('/:id', async (req, res) => {
  const { id } = req.params;
  const query = `DELETE FROM Genres WHERE GenreId = @GenreId`;
  try {
    const pool = await getPool();
    await pool.request()
      .input('GenreId', id)
      .query(`DELETE FROM MovieGenres WHERE GenreId = @GenreId`);
    await pool.request().input('GenreId', id).query(query);
    res.json({ message: "Genre deleted successfully" });
  } catch (error) {
    console.error("Error deleting genre:", error);
    res.status(500).json({ error: "Internal server error" });
  }
});

export default router;