import express from "express";
import { getPool } from '../db.js';

const router = express.Router();

/** 
 * GET all people
 * /api/people
 */
router.get('/', async (req, res) => {
  try {
    const pool = await getPool();
    const result = await pool.request().query("SELECT * FROM People");
    res.json(result.recordset);
  } catch (err) {
    console.error("Error fetching people:", err);
    res.status(500).json({ error: "Failed to fetch people" });
  }
});

/**
 * GET a specific person
 * /api/people/:id
 */ 
router.get('/:id', async (req, res) => {
  const personId = req.params.id;
  try {
    const pool = await getPool();
    const result = await pool
      .request()
      .input('PersonId', personId)
      .query('SELECT * FROM People WHERE PersonId = @PersonId');
    if (result.recordset.length === 0) {
      return res.status(404).json({ error: "Person not found" });
    }
    res.json(result.recordset[0]);
  } catch (error) {
    console.error("Error fetching person:", error);
    res.status(500).json({ error: "Internal server error" });
  }
});

/**
 * GET the movies a specific person is in
 * /api/people/:id/movies 
 */
router.get('/:id/movies', async (req, res) => {
  const personId = req.params.id;
  const query = `SELECT Movies.* FROM MoviePeople JOIN Movies ON MoviePeople.MovieId = Movies.MovieId WHERE MoviePeople.personId = @personId`;
  try {
    const pool = await getPool();
    const result = await pool
      .request()
      .input('PersonId', personId)
      .query(query);
    res.json(result.recordset);
  } catch (error) {
    console.error("Error fetching movies this person is in:", error);
    res.status(500).json({ error: "Internal server error" });
  }
});

/**
 * POST (create) a new person
 * /api/people
 */
router.post('/', async (req, res) => {
  const { FirstName, LastName } = req.body;
  if (!FirstName || !LastName) {
    return res.status(400).json({ error: "FirstName and LastName are required" });
  }
  try {
    const pool = await getPool();
    const result = await pool.request()
      .input("FirstName", FirstName)
      .input("LastName", LastName)
      .query(`INSERT INTO People (FirstName, LastName) OUTPUT INSERTED.* VALUES (@FirstName, @LastName)`);
    // result.recordset[0] contains the new row, including the autogenerated PersonId
    res.status(201).json(result.recordset[0]);
  } catch (err) {
    console.error("Error inserting person:", err);
    res.status(500).json({ error: "Internal server error" });
  }
});

/**
 * PUT (updatre) a person
 * /api/people/:id
 */
router.put('/:id', async (req, res) => {
  const { id } = req.params;
  const { FirstName, LastName } = req.body;
  const query = `UPDATE People SET FirstName = @FirstName, LastName = @LastName WHERE PersonId = @PersonId`;
  try {
    const pool = await getPool();
    await pool.request()
      .input('PersonId', id)
      .input('FirstName', FirstName)
      .input('LastName', LastName)
      .query(query);
    res.json({ message: "Person updated successfully" });
  } catch (error) {
    console.error("Error updating person:", error);
    res.status(500).json({ error: "Internal server error" });
  }
});

/**
 * DELETE a person
 * /api/people/:id
 */
router.delete('/:id', async (req, res) => {
  const { id } = req.params;
  const query = `DELETE FROM People WHERE PersonId = @PersonId`;
  try {
    const pool = await getPool();
    await pool.request()
      .input('PersonId', id)
      .query(`DELETE FROM MoviePeople WHERE PersonId = @PersonId`);
    await pool.request()
      .input('PersonId', id)
      .query(query);
    res.json({ message: "Person deleted successfully" });
  } catch (error) {
    console.error("Error deleting person:", error);
    res.status(500).json({ error: "Internal server error" });
  }
});

export default router;