import express from "express";
import { getPool } from '../db.js';

const router = express.Router();

/** 
 * GET all sales
 * /api/sales
 */
router.get('/', async (req, res) => {
  try {
    const pool = await getPool();
    const result = await pool.request().query("SELECT * FROM Sales");
    res.json(result.recordset);
  } catch (err) {
    console.error("Error fetching sales:", err);
    res.status(500).json({ error: "Failed to fetch sales" });
  }
});

/**
 * GET a specific sale
 * /api/sale/:id
 */ 
router.get('/:id', async (req, res) => {
  const saleId = req.params.id;
  try {
    const pool = await getPool();
    const result = await pool
      .request()
      .input('SaleId', saleId)
      .query('SELECT * FROM Sales WHERE SaleId = @SaleId');
    if (result.recordset.length === 0) {
      return res.status(404).json({ error: "Sale not found" });
    }
    res.json(result.recordset[0]);
  } catch (error) {
    console.error("Error fetching sale:", error);
    res.status(500).json({ error: "Internal server error" });
  }
});

/**
 * GET the movies that are part of a specific sale
 * /api/sales/:id/movies
 */
router.get('/:id/movies', async (req, res) => {
  const saleId = req.params.id;
  const query = `SELECT Movies.* FROM movieSales JOIN Movies ON MovieSales.MovieId = Movies.MovieId WHERE MovieSales.SaleId = @SaleId`;
  try {
    const pool = await getPool();
    const result = await pool
      .request()
      .input('SaleId', saleId)
      .query(query);
    res.json(result.recordset);
  } catch (error) {
    console.error("Error fetching movies that are a part of this sale:", error);
    res.status(500).json({ error: "Internal server error" });
  }
});

/**
 * POST (create) a new sale
 * /api/sale
 */
router.post('/', async (req, res) => {
  const { Discount, StartDate, EndDate, Category } = req.body;
  if (!Discount || !StartDate || !EndDate || !Category) {
    return res.status(400).json({ error: "Discount, StartDate, EndDate, and Category are required" });
  }
  try {
    const pool = await getPool();
    const result = await pool.request()
      .input("Discount", Discount)
      .input("StartDate", StartDate)
      .input("EndDate", EndDate)
      .input("Category", Category)
      .query(`INSERT INTO Sales (Discount, StartDate, EndDate, Category) OUTPUT INSERTED.* VALUES (@Discount, @StartDate, @EndDate, @Category)`);
    // result.recordset[0] contains the new row, including the autogenerated SaleId
    res.status(201).json(result.recordset[0]);

  } catch (err) {
    console.error("Error inserting sale:", err);
    res.status(500).json({ error: "Internal server error" });
  }
});

/**
 * PUT (updatre) a sale
 * /api/sales/:id
 */
router.put('/:id', async (req, res) => {
  const { id } = req.params;
  const { Discount, StartDate, EndDate, Category } = req.body;
  const query = `UPDATE Sales SET Discount = @Discount, StartDate = @StartDate, EndDate = @EndDate, Category = @Category WHERE SaleId = @SaleId`;
  try {
    const pool = await getPool();
    await pool.request()
      .input('SaleId', id)
      .input("Discount", Discount)
      .input("StartDate", StartDate)
      .input("EndDate", EndDate)
      .input("Category", Category)
      .query(query);
    res.json({ message: "Sale updated successfully" });
  } catch (error) {
    console.error("Error updating sale:", error);
    res.status(500).json({ error: "Internal server error" });
  }
});

/**
 * DELETE a sale
 * /api/sales/:id
 */
router.delete('/:id', async (req, res) => {
  const { id } = req.params;
  const query = `DELETE FROM Sales WHERE SaleId = @SaleId`;
  try {
    const pool = await getPool();
    await pool.request()
      .input('SaleId', id)
      .query(`DELETE FROM MovieSales WHERE SaleId = @SaleId`);
    await pool.request().input('SaleId', id).query(query);
    res.json({ message: "Sale deleted successfully" });
  } catch (error) {
    console.error("Error deleting sale:", error);
    res.status(500).json({ error: "Internal server error" });
  }
});

export default router;