import express from "express";
import { getPool } from '../db.js';

const router = express.Router();

/** 
 * GET all users
 * /api/users
 */
router.get('/', async (req, res) => {
  try {
    const pool = await getPool();
    const result = await pool.request().query("SELECT * FROM Users");
    res.json(result.recordset);
  } catch (err) {
    console.error("Error fetching users:", err);
    res.status(500).json({ error: "Failed to fetch users" });
  }
});

/**
 * GET a specific user
 * /api/user/:id
 */ 
router.get('/:id', async (req, res) => {
  const userId = req.params.id;
  try {
    const pool = await getPool();
    const result = await pool
      .request()
      .input('UserId', userId)
      .query('SELECT * FROM Users WHERE UserId = @UserId');
    if (result.recordset.length === 0) {
      return res.status(404).json({ error: "User not found" });
    }
    res.json(result.recordset[0]);
  } catch (error) {
    console.error("Error fetching User:", error);
    res.status(500).json({ error: "Internal server error" });
  }
});

/**
 * GET a specific user's cart
 * /api/user/:id/carts
 */
router.get('/:id/carts', async (req, res) => {
  const userId = req.params.id;
  const query = `SELECT Carts.CartId, Orders.OrderId, Movies.MovieId, Movies.Title, Movies.Price FROM Carts LEFT JOIN Orders ON Carts.CartId = Orders.CartId LEFT JOIN Movies ON Orders.MovieId = Movies.MovieId WHERE Carts.UserId = @UserId`;
  try {
    const pool = await getPool();
    const result = await pool
      .request()
      .input('UserId', userId)
      .query(query);
    res.json(result.recordset);
  } catch (error) {
    console.error("Error fetching user's carts:", error);
    res.status(500).json({ error: "Internal server error" });
  }
});

/**
 * GET a specific user's reviews
 * /api/user/:id/reviews
 */
router.get('/:id/reviews', async (req, res) => {
  const userId = req.params.id;
  const query = `SELECT ReviewId, CriticId, ReviewDescription, Rating FROM Reviews WHERE CriticId = @UserId`;
  try {
    const pool = await getPool();
    const result = await pool
      .request()
      .input('UserId', userId)
      .query(query);
    res.json(result.recordset);
  } catch (error) {
    console.error("Error fetching user's carts:", error);
    res.status(500).json({ error: "Internal server error" });
  }
});

/**
 * POST (create) a new user and a new cart for the user
 * /api/users
 */
router.post('/', async (req, res) => {
  const { UserName, PasswordHash } = req.body;
  if (!UserName || !PasswordHash) {
    return res.status(400).json({ error: "Username and PasswordHash are required" });
  }
  try {
    const pool = await getPool();
    const userResult = await pool.request()
      .input("UserName", UserName)
      .input("PasswordHash", PasswordHash)
      .query(`INSERT INTO Users (UserName, PasswordHash) OUTPUT INSERTED.* VALUES (@UserName, @PasswordHash)`);
    const newUser = userResult.recordset[0];
    await pool.request()
      .input("UserId", newUser.UserId)
      .query(`INSERT INTO Carts (UserId) VALUES (@UserId)`);
    // result.recordset[0] contains the new row, including the autogenerated UserId
    res.status(201).json({message: "User and cart created successfully", user: newUser});
  } catch (err) {
    console.error("Error inserting user and cart:", err);
    res.status(500).json({ error: "Internal server error" });
  }
});

/**
 * PUT (update) a user
 * /api/users/:id
 */
router.put('/:id', async (req, res) => {
  const { id } = req.params;
  const { UserName, PasswordHash } = req.body;
  const query = `UPDATE Users SET UserName = @UserName, PasswordHash = @PasswordHash WHERE UserId = @UserId`;
  try {
    const pool = await getPool();
    await pool.request()
      .input('UserId', id)
      .input("UserName", UserName)
      .input("PasswordHash", PasswordHash)
      .query(query);
    res.json({ message: "User updated successfully" });
  } catch (error) {
    console.error("Error updating user:", error);
    res.status(500).json({ error: "Internal server error" });
  }
});

/**
 * DELETE a user and their cart
 * /api/users/:id
 */
router.delete('/:id', async (req, res) => {
  const { id } = req.params;
  try {
    const pool = await getPool();
    await pool.request()
      .input("UserId", id)
      .query(`DELETE FROM Carts WHERE UserId = @UserId`);
    await pool.request()
      .input("UserId", id)
      .query(`DELETE FROM Users WHERE UserId = @UserId`);
    res.json({ message: "User and cart deleted successfully" });
  } catch (error) {
    console.error("Error deleting user and cart:", error);
    res.status(500).json({ error: "Internal server error" });
  }
});

export default router;